//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geodesyx.STaskStatusChange {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="STaskStatusChange.IOracleWcfService")]
    public interface IOracleWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/ExecuteNonQuery", ReplyAction="http://tempuri.org/IOracleWcfService/ExecuteNonQueryResponse")]
        int ExecuteNonQuery(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/ExecuteNonQuery", ReplyAction="http://tempuri.org/IOracleWcfService/ExecuteNonQueryResponse")]
        System.Threading.Tasks.Task<int> ExecuteNonQueryAsync(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequence", ReplyAction="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequenceResponse")]
        int SelectCurrentFromSequence(string sequence_name, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequence", ReplyAction="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequenceResponse")]
        System.Threading.Tasks.Task<int> SelectCurrentFromSequenceAsync(string sequence_name, string connectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOracleWcfServiceChannel : Geodesyx.STaskStatusChange.IOracleWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OracleWcfServiceClient : System.ServiceModel.ClientBase<Geodesyx.STaskStatusChange.IOracleWcfService>, Geodesyx.STaskStatusChange.IOracleWcfService {
        
        public OracleWcfServiceClient() {
        }
        
        public OracleWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OracleWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OracleWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OracleWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ExecuteNonQuery(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString) {
            return base.Channel.ExecuteNonQuery(query, param, connectionString);
        }
        
        public System.Threading.Tasks.Task<int> ExecuteNonQueryAsync(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString) {
            return base.Channel.ExecuteNonQueryAsync(query, param, connectionString);
        }
        
        public int SelectCurrentFromSequence(string sequence_name, string connectionString) {
            return base.Channel.SelectCurrentFromSequence(sequence_name, connectionString);
        }
        
        public System.Threading.Tasks.Task<int> SelectCurrentFromSequenceAsync(string sequence_name, string connectionString) {
            return base.Channel.SelectCurrentFromSequenceAsync(sequence_name, connectionString);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="STaskStatusChange.ITaskStatusChange")]
    public interface ITaskStatusChange {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskStatusChange/Insert", ReplyAction="http://tempuri.org/ITaskStatusChange/InsertResponse")]
        int Insert(DTOlib.TaskStatusChange input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskStatusChange/Insert", ReplyAction="http://tempuri.org/ITaskStatusChange/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(DTOlib.TaskStatusChange input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskStatusChange/Select", ReplyAction="http://tempuri.org/ITaskStatusChange/SelectResponse")]
        System.Collections.Generic.List<DTOlib.TaskStatusChange> Select(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskStatusChange/Select", ReplyAction="http://tempuri.org/ITaskStatusChange/SelectResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.TaskStatusChange>> SelectAsync(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskStatusChange/SelectNewTasks", ReplyAction="http://tempuri.org/ITaskStatusChange/SelectNewTasksResponse")]
        System.Collections.Generic.List<DTOlib.TaskStatusChange> SelectNewTasks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskStatusChange/SelectNewTasks", ReplyAction="http://tempuri.org/ITaskStatusChange/SelectNewTasksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.TaskStatusChange>> SelectNewTasksAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskStatusChangeChannel : Geodesyx.STaskStatusChange.ITaskStatusChange, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskStatusChangeClient : System.ServiceModel.ClientBase<Geodesyx.STaskStatusChange.ITaskStatusChange>, Geodesyx.STaskStatusChange.ITaskStatusChange {
        
        public TaskStatusChangeClient() {
        }
        
        public TaskStatusChangeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskStatusChangeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskStatusChangeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskStatusChangeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Insert(DTOlib.TaskStatusChange input) {
            return base.Channel.Insert(input);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(DTOlib.TaskStatusChange input) {
            return base.Channel.InsertAsync(input);
        }
        
        public System.Collections.Generic.List<DTOlib.TaskStatusChange> Select(System.Collections.Generic.List<int> ids) {
            return base.Channel.Select(ids);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.TaskStatusChange>> SelectAsync(System.Collections.Generic.List<int> ids) {
            return base.Channel.SelectAsync(ids);
        }
        
        public System.Collections.Generic.List<DTOlib.TaskStatusChange> SelectNewTasks() {
            return base.Channel.SelectNewTasks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.TaskStatusChange>> SelectNewTasksAsync() {
            return base.Channel.SelectNewTasksAsync();
        }
    }
}
