//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geodesyx.SRequest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRequest.IOracleWcfService")]
    public interface IOracleWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/ExecuteNonQuery", ReplyAction="http://tempuri.org/IOracleWcfService/ExecuteNonQueryResponse")]
        int ExecuteNonQuery(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/ExecuteNonQuery", ReplyAction="http://tempuri.org/IOracleWcfService/ExecuteNonQueryResponse")]
        System.Threading.Tasks.Task<int> ExecuteNonQueryAsync(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequence", ReplyAction="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequenceResponse")]
        int SelectCurrentFromSequence(string sequence_name, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequence", ReplyAction="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequenceResponse")]
        System.Threading.Tasks.Task<int> SelectCurrentFromSequenceAsync(string sequence_name, string connectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOracleWcfServiceChannel : Geodesyx.SRequest.IOracleWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OracleWcfServiceClient : System.ServiceModel.ClientBase<Geodesyx.SRequest.IOracleWcfService>, Geodesyx.SRequest.IOracleWcfService {
        
        public OracleWcfServiceClient() {
        }
        
        public OracleWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OracleWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OracleWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OracleWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ExecuteNonQuery(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString) {
            return base.Channel.ExecuteNonQuery(query, param, connectionString);
        }
        
        public System.Threading.Tasks.Task<int> ExecuteNonQueryAsync(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString) {
            return base.Channel.ExecuteNonQueryAsync(query, param, connectionString);
        }
        
        public int SelectCurrentFromSequence(string sequence_name, string connectionString) {
            return base.Channel.SelectCurrentFromSequence(sequence_name, connectionString);
        }
        
        public System.Threading.Tasks.Task<int> SelectCurrentFromSequenceAsync(string sequence_name, string connectionString) {
            return base.Channel.SelectCurrentFromSequenceAsync(sequence_name, connectionString);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRequest.IRequest")]
    public interface IRequest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/SelectAll", ReplyAction="http://tempuri.org/IRequest/SelectAllResponse")]
        System.Collections.Generic.List<DTOlib.Request> SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/SelectAll", ReplyAction="http://tempuri.org/IRequest/SelectAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.Request>> SelectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/SelectNewRequests", ReplyAction="http://tempuri.org/IRequest/SelectNewRequestsResponse")]
        System.Collections.Generic.List<DTOlib.Request> SelectNewRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/SelectNewRequests", ReplyAction="http://tempuri.org/IRequest/SelectNewRequestsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.Request>> SelectNewRequestsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/Select", ReplyAction="http://tempuri.org/IRequest/SelectResponse")]
        DTOlib.Request Select(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/Select", ReplyAction="http://tempuri.org/IRequest/SelectResponse")]
        System.Threading.Tasks.Task<DTOlib.Request> SelectAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/Insert", ReplyAction="http://tempuri.org/IRequest/InsertResponse")]
        int Insert(DTOlib.Request input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/Insert", ReplyAction="http://tempuri.org/IRequest/InsertResponse")]
        System.Threading.Tasks.Task<int> InsertAsync(DTOlib.Request input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/Update", ReplyAction="http://tempuri.org/IRequest/UpdateResponse")]
        int Update(int id, string name, string desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequest/Update", ReplyAction="http://tempuri.org/IRequest/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(int id, string name, string desc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequestChannel : Geodesyx.SRequest.IRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestClient : System.ServiceModel.ClientBase<Geodesyx.SRequest.IRequest>, Geodesyx.SRequest.IRequest {
        
        public RequestClient() {
        }
        
        public RequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<DTOlib.Request> SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.Request>> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
        
        public System.Collections.Generic.List<DTOlib.Request> SelectNewRequests() {
            return base.Channel.SelectNewRequests();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.Request>> SelectNewRequestsAsync() {
            return base.Channel.SelectNewRequestsAsync();
        }
        
        public DTOlib.Request Select(int id) {
            return base.Channel.Select(id);
        }
        
        public System.Threading.Tasks.Task<DTOlib.Request> SelectAsync(int id) {
            return base.Channel.SelectAsync(id);
        }
        
        public int Insert(DTOlib.Request input) {
            return base.Channel.Insert(input);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(DTOlib.Request input) {
            return base.Channel.InsertAsync(input);
        }
        
        public int Update(int id, string name, string desc) {
            return base.Channel.Update(id, name, desc);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(int id, string name, string desc) {
            return base.Channel.UpdateAsync(id, name, desc);
        }
    }
}
