//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geodesyx.SBrigadeNewTasks {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SBrigadeNewTasks.IOracleWcfService")]
    public interface IOracleWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/ExecuteNonQuery", ReplyAction="http://tempuri.org/IOracleWcfService/ExecuteNonQueryResponse")]
        int ExecuteNonQuery(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/ExecuteNonQuery", ReplyAction="http://tempuri.org/IOracleWcfService/ExecuteNonQueryResponse")]
        System.Threading.Tasks.Task<int> ExecuteNonQueryAsync(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequence", ReplyAction="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequenceResponse")]
        int SelectCurrentFromSequence(string sequence_name, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequence", ReplyAction="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequenceResponse")]
        System.Threading.Tasks.Task<int> SelectCurrentFromSequenceAsync(string sequence_name, string connectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOracleWcfServiceChannel : Geodesyx.SBrigadeNewTasks.IOracleWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OracleWcfServiceClient : System.ServiceModel.ClientBase<Geodesyx.SBrigadeNewTasks.IOracleWcfService>, Geodesyx.SBrigadeNewTasks.IOracleWcfService {
        
        public OracleWcfServiceClient() {
        }
        
        public OracleWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OracleWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OracleWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OracleWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ExecuteNonQuery(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString) {
            return base.Channel.ExecuteNonQuery(query, param, connectionString);
        }
        
        public System.Threading.Tasks.Task<int> ExecuteNonQueryAsync(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString) {
            return base.Channel.ExecuteNonQueryAsync(query, param, connectionString);
        }
        
        public int SelectCurrentFromSequence(string sequence_name, string connectionString) {
            return base.Channel.SelectCurrentFromSequence(sequence_name, connectionString);
        }
        
        public System.Threading.Tasks.Task<int> SelectCurrentFromSequenceAsync(string sequence_name, string connectionString) {
            return base.Channel.SelectCurrentFromSequenceAsync(sequence_name, connectionString);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SBrigadeNewTasks.IBrigadeNewTasks")]
    public interface IBrigadeNewTasks {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeNewTasks/SelectAll", ReplyAction="http://tempuri.org/IBrigadeNewTasks/SelectAllResponse")]
        System.Collections.Generic.List<DTOlib.VBrigadeNewTasks> SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeNewTasks/SelectAll", ReplyAction="http://tempuri.org/IBrigadeNewTasks/SelectAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.VBrigadeNewTasks>> SelectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeNewTasks/SelectIn", ReplyAction="http://tempuri.org/IBrigadeNewTasks/SelectInResponse")]
        System.Collections.Generic.List<DTOlib.VBrigadeNewTasks> SelectIn(System.Collections.Generic.List<int> task_ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeNewTasks/SelectIn", ReplyAction="http://tempuri.org/IBrigadeNewTasks/SelectInResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.VBrigadeNewTasks>> SelectInAsync(System.Collections.Generic.List<int> task_ids);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrigadeNewTasksChannel : Geodesyx.SBrigadeNewTasks.IBrigadeNewTasks, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrigadeNewTasksClient : System.ServiceModel.ClientBase<Geodesyx.SBrigadeNewTasks.IBrigadeNewTasks>, Geodesyx.SBrigadeNewTasks.IBrigadeNewTasks {
        
        public BrigadeNewTasksClient() {
        }
        
        public BrigadeNewTasksClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrigadeNewTasksClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrigadeNewTasksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrigadeNewTasksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<DTOlib.VBrigadeNewTasks> SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.VBrigadeNewTasks>> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
        
        public System.Collections.Generic.List<DTOlib.VBrigadeNewTasks> SelectIn(System.Collections.Generic.List<int> task_ids) {
            return base.Channel.SelectIn(task_ids);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.VBrigadeNewTasks>> SelectInAsync(System.Collections.Generic.List<int> task_ids) {
            return base.Channel.SelectInAsync(task_ids);
        }
    }
}
