//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geodesyx.SBrigadeEndedTasks {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SBrigadeEndedTasks.IOracleWcfService")]
    public interface IOracleWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/ExecuteNonQuery", ReplyAction="http://tempuri.org/IOracleWcfService/ExecuteNonQueryResponse")]
        int ExecuteNonQuery(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/ExecuteNonQuery", ReplyAction="http://tempuri.org/IOracleWcfService/ExecuteNonQueryResponse")]
        System.Threading.Tasks.Task<int> ExecuteNonQueryAsync(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequence", ReplyAction="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequenceResponse")]
        int SelectCurrentFromSequence(string sequence_name, string connectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequence", ReplyAction="http://tempuri.org/IOracleWcfService/SelectCurrentFromSequenceResponse")]
        System.Threading.Tasks.Task<int> SelectCurrentFromSequenceAsync(string sequence_name, string connectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOracleWcfServiceChannel : Geodesyx.SBrigadeEndedTasks.IOracleWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OracleWcfServiceClient : System.ServiceModel.ClientBase<Geodesyx.SBrigadeEndedTasks.IOracleWcfService>, Geodesyx.SBrigadeEndedTasks.IOracleWcfService {
        
        public OracleWcfServiceClient() {
        }
        
        public OracleWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OracleWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OracleWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OracleWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ExecuteNonQuery(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString) {
            return base.Channel.ExecuteNonQuery(query, param, connectionString);
        }
        
        public System.Threading.Tasks.Task<int> ExecuteNonQueryAsync(string query, System.Collections.Generic.List<Oracle.ManagedDataAccess.Client.OracleParameter> param, string connectionString) {
            return base.Channel.ExecuteNonQueryAsync(query, param, connectionString);
        }
        
        public int SelectCurrentFromSequence(string sequence_name, string connectionString) {
            return base.Channel.SelectCurrentFromSequence(sequence_name, connectionString);
        }
        
        public System.Threading.Tasks.Task<int> SelectCurrentFromSequenceAsync(string sequence_name, string connectionString) {
            return base.Channel.SelectCurrentFromSequenceAsync(sequence_name, connectionString);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SBrigadeEndedTasks.IBrigadeEndedTasks")]
    public interface IBrigadeEndedTasks {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeEndedTasks/SelectAll", ReplyAction="http://tempuri.org/IBrigadeEndedTasks/SelectAllResponse")]
        System.Collections.Generic.List<DTOlib.VBrigadeEndedTasks> SelectAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeEndedTasks/SelectAll", ReplyAction="http://tempuri.org/IBrigadeEndedTasks/SelectAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.VBrigadeEndedTasks>> SelectAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeEndedTasks/SelectIn", ReplyAction="http://tempuri.org/IBrigadeEndedTasks/SelectInResponse")]
        System.Collections.Generic.List<DTOlib.VBrigadeEndedTasks> SelectIn(System.Collections.Generic.List<int> task_ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrigadeEndedTasks/SelectIn", ReplyAction="http://tempuri.org/IBrigadeEndedTasks/SelectInResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.VBrigadeEndedTasks>> SelectInAsync(System.Collections.Generic.List<int> task_ids);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBrigadeEndedTasksChannel : Geodesyx.SBrigadeEndedTasks.IBrigadeEndedTasks, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BrigadeEndedTasksClient : System.ServiceModel.ClientBase<Geodesyx.SBrigadeEndedTasks.IBrigadeEndedTasks>, Geodesyx.SBrigadeEndedTasks.IBrigadeEndedTasks {
        
        public BrigadeEndedTasksClient() {
        }
        
        public BrigadeEndedTasksClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BrigadeEndedTasksClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrigadeEndedTasksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BrigadeEndedTasksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<DTOlib.VBrigadeEndedTasks> SelectAll() {
            return base.Channel.SelectAll();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.VBrigadeEndedTasks>> SelectAllAsync() {
            return base.Channel.SelectAllAsync();
        }
        
        public System.Collections.Generic.List<DTOlib.VBrigadeEndedTasks> SelectIn(System.Collections.Generic.List<int> task_ids) {
            return base.Channel.SelectIn(task_ids);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DTOlib.VBrigadeEndedTasks>> SelectInAsync(System.Collections.Generic.List<int> task_ids) {
            return base.Channel.SelectInAsync(task_ids);
        }
    }
}
